### PR TITLE
The last VR fix was a messup, this one might work better

### PR DESCRIPTION
**Pull request by BoxxRoss**
due to the last pull request, the c4 brick just dosent appear when in vr mode now, thats cause i was missing a few things that should now be fully impelneted, im not sure about the other changes you've made to the VR checks for the mod, but this version i have now could still break.

### CODE REVIEW

**Comment by BoxxRoss** [comment]
the more i look at this the more i realize i need some more time to figure this out, if you can, revert the changes made by my last pull

**Comment by Moffein** [comment]
Already rewrote most of the code you sent previously. If you could confirm the current version on Thunderstore works, that would be great. Otherwise, for future pull requests it would be best if you could confirm the stuff actually works on your end first before sending them in.

**Comment by DrBibop** [comment]
Just chiming in to comment on the modification on the previous PR: Checking for IsInVR() is redundant, as it is already being checked in IsUsingMotionControls().

**Comment by BoxxRoss** [comment]
so i just tested it and the c4 still doesn't appear when you click the button, me pushing the fork when i had not tested it yet was stupid of me, honestly ive been stressing over this for a good hour at this point and i think im gonna take a break, either way, the problem before was minor so it would probably be best to revert the vr stuff for now and return it to how it was before the pull request, you should also probably remove me and the vr mentions on the thunderstorm mod page, if i ever do come back it should be with a much more tested change

**Comment by DrBibop** [comment]
Do you have the VRAPI mod installed? I'd say it would be the only reason why it wouldn't work

**Comment by BoxxRoss** [comment]
yea i got it installed, it always is.

**Comment by Moffein** [comment]
> Just chiming in to comment on the modification on the previous PR: Checking for IsInVR() is redundant, as it is already being checked in IsUsingMotionControls().

Noted, updated the mod with this. I'd like to get this working in one go rather than having to revert then update again, so any insight into this would be helpful since I don't have a VR headset to test with.

**Comment by BoxxRoss** [comment]
im willing to keep testing them to see if the changes helped

**Comment by BoxxRoss** [comment]
its still broken unfortunately

**Comment by BoxxRoss** [comment]
if you wanna get this solved your probably gonna wanna talk to DRBibop since he def knows more than me. me and him were talking a lot in the Flat 2 VR discord in the ror2 help section, if you want some more advice, id say talk to him there or look through to see what he told me. I also want to apologize again about the PR blunder earlier, i probably shoudla figured out some way to test it first

**Comment by Moffein** [comment]
Fixed as of the latest update.

**Pull request closed without merging**
